### ISSUE TITLE
Proposed bcbio upgrade

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#219]
Those that use bcbio would like an upgrade but no one is quite sure yet what it should be upgraded to.
Here is the proposed installation script to kick off the discussion

```
#!/bin/bash
#$ -l rmem=32G -l mem=32G
#$ -P radiant

module load apps/binapps/anacondapython/2.3
module load compilers/gcc/5.2
module load apps/gcc/5.2/git/2.5
module load apps/R/3.2.1
module load apps/java/1.7

install_dir=/fastdata/testing123/NEW_bcbio
mkdir -p $install_dir

wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py

python bcbio_nextgen_install.py $install_dir --tooldir=$install_dir/tools --isolate \
   --genomes hg38 --aligners bwa --aligners bowtie2
```

**Comment by mikecroucher** [comment]
From email discussions, it seems we need

* hg38 and hisat2
* h19 and STAR

So I need the installation incantation. Using our development version of bcbio, I did

  bcbio_nextgen.py upgrade -h

which gives all the options for genomes and aligners. From this, I took a guess at 

    python bcbio_nextgen_install.py $install_dir --tooldir=$install_dir/tools --isolate \
       --genomes hg38 --genomes hg19 \
       --aligners bwa --aligners bowtie2 --aligners hisat2 --aligners star

Which our bcbio contact thinks should do the job.

**Comment by mikecroucher** [comment]
It turns out that you can’t request hisat2 at install time. You get the following error message

```
usage: bcbio_nextgen_install.py [-h] [--tooldir TOOLDIR] [--toolplus TOOLPLUS]
                                [--genomes {GRCh37,hg19,hg38,hg38-noalt,mm10,mm9,rn6,rn5,canFam3,dm3,galGal4,phix,pseudomonas_aeruginosa_ucbpp_pa14,sacCer3,TAIR10,WBcel235,xenTro3,Zv9,GRCz10}]
                                [--aligners {bowtie,bowtie2,bwa,novoalign,rtg,snap,star,ucsc}]
                                [--nodata] [--isolate]
                                [-u {stable,development}]
                                [--distribution {ubuntu,debian,centos,scientificlinux,macosx}]
                                datadir
bcbio_nextgen_install.py: error: argument --aligners: invalid choice: 'hisat2' (choose from 'bowtie', 'bowtie2', 'bwa', 'novoalign', 'rtg', 'snap', 'star', 'ucsc’)
```

I assume that one has to install base bcbio and then use the upgrade command to get hisat2. 
I attempted to do this over the weekend but the bcbio installer appears to be quite brittle.

Over the weekend, it failed with the error 
```
Error: HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/bioconda/linux-64/perl-ipc-system-simple-1.25-pl5.22.0_0.tar.bz2: https://conda.anaconda.org/bioconda/linux-64/perl-ipc-system-simple-1.25-pl5.22.0_0.tar.bz2
```

This morning it failed with the error
```
Error: HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/bioconda/linux-64/bioconductor-geneplotter-1.48.0-0.tar.bz2: https://conda.anaconda.org/bioconda/linux-64/bioconductor-geneplotter-1.48.0-0.tar.bz2
```
These 404 errors appear to be transient. I’m currently running another attempt at an install.

**Comment by mikecroucher** [comment]
I'm starting from scratch each time since I don't know what state the install is in after a failure. Every new attempt gets a new 404 error. Here's my next attempt

```
Error: HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/bioconda/linux-64/manta-0.29.1-py27_0.tar.bz2: https://conda.anaconda.org/bioconda/linux-64/manta-0.29.1-py27_0.tar.bz2
```

**Comment by mikecroucher** [comment]
The bcbio team informed me that I could just rerun the installer if it fails on a 404 like this and it would cleanly pick up where it left off. Did this last night. 

13 hours later, it's still installing! Here's the relevant line from top

    25060 fe4user    20   0 19.5g  19g 1116 R 100.0 30.9 804:54.27 STAR

**Comment by mikecroucher** [comment]
Still running...almost 2 days later. I emailed the bcbio team and included the info:

Been stuck for almost a couple of days now…

```
bowtie2/hg19.4.bt2
bowtie2/hg19.2.bt2
bowtie2/hg19.1.bt2
Dec 21 19:59:02 ..... Started STAR run
Dec 21 19:59:02 ... Starting to generate Genome files
Dec 21 20:00:55 ... starting to sort  Suffix Array. This may take a long time...
Dec 21 20:01:12 ... sorting Suffix Array chunks and saving them to disk...
```

This was the last output I saw.
STAR seems to be exercising 100% of a core with no end in sight.

The reply from the bcbio team was

this is an issue with STAR 2.5.0 that has been fixed, but a new release hasn’t been rolled yet:  https://github.com/alexdobin/STAR/issues/86

**Comment by mikecroucher** [comment]
They've fixed the STAR issue and I'm trying again

**Comment by mikecroucher** [comment]
Failed with a 404 error. Restarting from where it left off

**Comment by mikecroucher** [comment]
The previous install is still running. The culprit is STAR again.

I wonder if I was a little premature in my retry. Perhaps the fix hadn't been folded in.
Trying  again

**Comment by mikecroucher** [comment]
The most recent install attempt was on December 28th. It is still running, using 100% of 1 CPU core, on January 4th. I've contacted the bcbio team again for advice.

**Comment by Cadair** [comment]
wow, that's impressive.

**Comment by mikecroucher** [comment]
output from top 

    35800 fe1mpc    20   0 19.5g  19g 1108 R 99.9 30.9   1102:48 STAR

Try an strace but get no output

    strace -p 35800
    Process 35800 attached

**Comment by mikecroucher** [comment]
Last few lines of stderr are 

    INFO: Genome preparation method s3 failed, trying next
    INFO: Genome preparation method s3 failed, trying next
    INFO: Preparing genome hg19 with index star
    INFO: Preparing genome hg19 with index star

Last few lines of stdout are 

    bowtie2/hg19.2.bt2
    bowtie2/hg19.1.bt2
    Jan 04 17:51:23 ..... Started STAR run
    Jan 04 17:51:23 ... Starting to generate Genome files
    Jan 04 17:52:43 ... starting to sort  Suffix Array. This may take a long time...
    Jan 04 17:53:01 ... sorting Suffix Array chunks and saving them to disk…

**Comment by mikecroucher** [comment]
Advised by winhide that we might be able to do without the STAR aligner. At the very least, we can install the rest of bcbio and worry about STAR later.

**Comment by mikecroucher** [comment]
Latest attempt failed 

```
INFO: Genome preparation method s3 failed, trying next
INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome hg19 with index hisat2
INFO: Preparing genome hg19 with index hisat2
INFO: Genome preparation method raw failed, trying next
INFO: Genome preparation method raw failed, trying next
Traceback (most recent call last):
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6a0', 'bcbio_nextgen.py')
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/anaconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 745, in run_script
    
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/anaconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1670, in run_script
    
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 257, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 349, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 488, in _prep_genomes
    raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
IOError: Could not prepare index hisat2 for hg19 by any method
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 241, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/local/packages6/apps/binapps/anacondapython/2.3/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.5/tools', '--isolate', '--genomes', 'hg38', '--genomes', 'hg19', '--aligners', 'bwa', '--aligners', 'bowtie2', '--aligners', 'hisat2', '--data']' returned non-zero exit status 1
```

Advice from bcbio guys: 

The problem is that we don’t have a general indexing strategy for hisat2 implemented because it can require a crazy amount (like 200 gigs) of memory. If you leave off hisat2 for the base install and then install it just for hg38 after the base install completes it will work around this issue and get you going.

**Comment by ssamberkar** [comment]
Thanks for the updates Mike..
So can I take it for a spin or the installation still on going??

**Comment by mikecroucher** [comment]
Still working through it. I'll let you know

**Comment by mikecroucher** [comment]
latest attempt failed.
Install script:

```
#!/bin/bash
#$ -l rmem=32G -l mem=32G
#$ -P radiant

module load apps/binapps/anacondapython/2.3
module load apps/gcc/5.2/git/2.5
module load apps/R/3.2.1
module load apps/java/1.7
module load compilers/gcc/5.2

install_dir=/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a
mkdir -p $install_dir

wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py

python bcbio_nextgen_install.py $install_dir --tooldir=$install_dir/tools --isolate \
   --genomes hg38 --genomes hg19 \
   --aligners bwa --aligners bowtie2
```

Failure:

```
--2016-01-06 12:03:33--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/2.8/hg19/dbsnp_138.hg19.vcf.gz
           => `dbsnp_138.hg19.vcf.gz'
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... 
Login incorrect.

Warning: local() encountered an error (return code 6) while executing 'wget --continue --no-check-certificate -O dbsnp_138.hg19.vcf.gz 'ftp://gsapubftp-anonymous:@ftp.broadinstitute.org/bundle/2.8/hg19/dbsnp_138.hg19.vcf.gz''

Traceback (most recent call last):
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6a0', 'bcbio_nextgen.py')
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 745, in run_script
    
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1670, in run_script
    
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 257, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 351, in install_data
    _install_additional_data(genomes, genome_indexes, config)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 391, in _install_additional_data
    download_dbsnp(genomes, BROAD_BUNDLE_VERSION, DBSNP_VERSION)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 39, in download_dbsnp
    _dbsnp_human(env, gid, manager, bundle_version, dbsnp_version)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 65, in _dbsnp_human
    _download_broad_bundle(manager.dl_name, bundle_version, dl_name, ext)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 86, in _download_broad_bundle
    out_file = shared._remote_fetch(env, base_url)
  File "/mnt/fastdata/fe1mpc/bcbio_install/tmpbcbio-install/cloudbiolinux/cloudbio/custom/shared.py", line 202, in _remote_fetch
    raise IOError("Failure to retrieve remote file")
IOError: Failure to retrieve remote file
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 241, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/local/packages6/apps/binapps/anacondapython/2.3/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/tools', '--isolate', '--genomes', 'hg38', '--genomes', 'hg19', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

**Comment by mikecroucher** [comment]
Info from the bcbio guys:

    Specially the issue here is that the Broad FTP server where we get reference
    genomes is pretty sketchy. It'll be down or over capacity at times, and the
    only fix is to wait and re-try.

This leads me to wonder how often are the reference genomes updated? Are they something for which a local mirror might be a good idea? How much storage might we need?

**Comment by ssamberkar** [comment]
Genomes are updated every 3-4 years. A local mirror is a good idea, one can just apply rsync over it to get the most updated release. More info here -- http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/

The hg38 build was released in Dec 2013 and the hg19 in Feb 2009.
They are quite modest in size, in order of few GBs.
Is there any way we could plug in the reference genomes with a local address (/this/are/ref/genomes) and "ask" bcbio to continue the installation?

**Comment by ssamberkar** [comment]
In case it helps, hisat2 indices are pre-calculated and available for download -- ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/data/.
I need the one for GRCh38 -- ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/data/grch38_tran.tar.gz

**Comment by mikecroucher** [comment]
This is now complete
