### ISSUE TITLE
bcbio -- mm10 not found error

### ISSUE THREAD

**Issue by ssamberkar** [rcgsheffield/iceberg_software#272]
Hi Mike (@roryk) and Mike (@mikecroucher),

Although mm10 has been installed with all index files required for star, looks like some intermediary files are missing. This is the error I'm getting at when I try running my mouse samples with mm10.

```
Traceback (most recent call last):
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a//tools/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6', 'bcbio_nextgen.py')
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script
    
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1649, in run_script
    
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 233, in rnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 357, in rnaseq_prep_samples
    [x[0]["description"] for x in samples]]])
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 255, in organize_samples
    return run_info.organize(*args)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 58, in organize
    item = add_reference_resources(item)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 145, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 199, in get_refs
    galaxy_config, data)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 151, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 261, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file mm10 samtools

```

**Comment by roryk** [comment]
What does the mm10 genome directory structure look like?

**Comment by ssamberkar** [comment]
It looks like this:
 `
4.0K	 Feb	22	07:52	_STARtmp
1.5G	 Feb	25	06:02	SAindex
21G	 Feb	25	06:02	SA
22K	 Feb	22	07:53	Log.out
677	 Feb	25	05:35	genomeParameters.txt
2.6G	 Feb	25	05:59	Genome
722	 Feb	25	05:36	chrStart.txt
912	 Feb	25	05:36	chrName.txt
1.4K	 Feb	25	05:36	chrNameLength.txt
493	 Feb	25	05:36	chrLength.txt
`

**Comment by roryk** [comment]
What are in the directories one up from that? There should be a seq directory as well.

The entry that is missing is in the bcbio/galaxy/tool-data directory, there is a file "sam_fa_indices.loc" that did not get updated with a pointer to where the genome is. Does that file exist? Does it have a mm10 entry?

**Comment by ssamberkar** [comment]
You're right, it is missing the mm10 entry.
Will it work if I add it manually?
How to fix it during installation itself, say for adding another genome for another organism, if the same issue arises?

**Comment by roryk** [comment]
Hi Sandeep,

It will work if you add it manually, but it should have been put in there in the first place. For new genomes, bcbio_setup_genome.py will update that file and put the entry there. I’m not sure why installing with bcbio_nextgen.py upgrade did not add it.

Best,

Rory

**Comment by ssamberkar** [comment]
Mike,

Could you please make the changes in this file
`
/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/galaxy/tool-data/sam_fa_indices.loc
`
and add this line
`
info\tmm10\t/usr/local/packages6/apps/gcc/5.2/bcbio/0.9.6a/genomes/Mmusculus/mm10/seq/mm10.fa
`
I know this is pasting the leaky bits but we could try installing another genome and check if this is reproducible.
Thanks.

**Comment by mikecroucher** [comment]
done
